# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpacket.proto\x12\x06packet\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\r\n\x0bPingRequest\"\x0e\n\x0cPingResponse\"1\n\x0b\x43hatRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\x0b\x43hatMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cLoginRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xb1\x01\n\rClientMessage\x12#\n\x04\x65\x63ho\x18\x01 \x01(\x0b\x32\x13.packet.EchoRequestH\x00\x12$\n\x04pong\x18\x02 \x01(\x0b\x32\x14.packet.PingResponseH\x00\x12#\n\x04\x63hat\x18\x03 \x01(\x0b\x32\x13.packet.ChatRequestH\x00\x12%\n\x05login\x18\x05 \x01(\x0b\x32\x14.packet.LoginRequestH\x00\x42\t\n\x07payload\"\x89\x01\n\rServerMessage\x12#\n\x04\x65\x63ho\x18\x01 \x01(\x0b\x32\x13.packet.EchoRequestH\x00\x12#\n\x04ping\x18\x02 \x01(\x0b\x32\x13.packet.PingRequestH\x00\x12#\n\x04\x63hat\x18\x03 \x01(\x0b\x32\x13.packet.ChatMessageH\x00\x42\t\n\x07payloadb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ECHOREQUEST._serialized_start=24
  _ECHOREQUEST._serialized_end=54
  _PINGREQUEST._serialized_start=56
  _PINGREQUEST._serialized_end=69
  _PINGRESPONSE._serialized_start=71
  _PINGRESPONSE._serialized_end=85
  _CHATREQUEST._serialized_start=87
  _CHATREQUEST._serialized_end=136
  _CHATMESSAGE._serialized_start=138
  _CHATMESSAGE._serialized_end=168
  _LOGINREQUEST._serialized_start=170
  _LOGINREQUEST._serialized_end=201
  _CLIENTMESSAGE._serialized_start=204
  _CLIENTMESSAGE._serialized_end=381
  _SERVERMESSAGE._serialized_start=384
  _SERVERMESSAGE._serialized_end=521
# @@protoc_insertion_point(module_scope)
